config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :products

  root 'home#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    has_role?(:admin)
  end

  def customer?
    has_role?(:customer)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :permitted_parameters, if: :devise_controller?

  protected

  def permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[firstname lastname phoneno city email passowrd])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[firstname lastname phoneno city email passowrd current_password])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:welcome]
  def welcome; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  load_and_authorize_resource
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update; end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  protected

  def product_params
    params.require(:product).permit(:title, :description, :color, :fabric)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/welcome.html.erb
<div class="wrapper"> 
<section id="header">
      <li class="logo"><%= link_to 'DEVSHOP',root_path %></li>

    <ul id="menu">
    <% if current_user %>
      <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Log In', new_user_session_path %></li>
      <li><%= link_to 'Create An Account', new_user_registration_path %></li>
    <% end %>
    </ul>
</section>
<%= render "shared/alerts" %>
    <div class="banner">
      <div class="banner-img"></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecomm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model:@product, local: true do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :color %>
    <%= form.text_field :color %>
  </p>
  <p>
    <%= form.label :fabric %>
    <%= form.text_field :fabric %>
  </p>      
  <p>
  <%= form.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= render "form" %>

app/views/products/index.html.erb
<h1>All Products</h1>

<% @products.each do |product| %>
    <h3><%= product.title %></h3>
    <p><%= product.description %></p>
    <b>Color: </b> <span><%= product.color %></span><br>
    <b>Fabric: </b> <span><%= product.fabric %></span>
    <hr>
<% end %>

app/views/products/new.html.erb
<h2>Add A Product</h2>
<%= render "form" %>

app/views/products/show.html.erb
<h2>Product Details</h2>
  <h3><%= @product.title %></h3>
  <p><%= @product.description %></p>
  <b>Color: </b> <span><%= @product.color %></span><br>
  <b>Fabric: </b> <span><%= @product.fabric %></span>

  <%= link_to "Edit Product", edit_product_path %>
  <%= link_to "Delete", product_path, method: :delete, data: {confirm: "Are you Sure?"} %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>